### ISSUE TITLE
Outdated BMP write code does not pad correctly.

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/introduction-to-python#1]
You have an old and buggy version of the BMP writer, which only works for certain widths of images. You need to replace the loop which writes the pixel data with:

        # Pixel data
        pixel_data_bookmark = bmp.tell()
        for row in reversed(pixels):  # BMP files are bottom to top
            row_data = bytes(row)
            bmp.write(row_data)
            padding = b'\x00' * ((4 - (len(row) % 4)) % 4)  # Pad row to multiple
                                                            # of four bytes
            bmp.write(padding)

**Comment by abingham** [comment]
Thanks for pointing that out. It should be fixed as of 5b03d20.
